name: Ministry Mapper
env:
  REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
  REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
  REACT_APP_FIREBASE_DB_URL: ${{ secrets.REACT_APP_FIREBASE_DB_URL }}
  REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
  REACT_APP_FIREBASE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_BUCKET }}
  REACT_APP_FIREBASE_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_SENDER_ID }}
  REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
on:
  push:
    branches:
      - staging
      - master

jobs:
  verify:
    if: github.event_name  == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Check code formatting
        run: npm run prettier
      - name: Run application test cases
        run: npm run test
      - name: Run application build
        run: npm run build
  deploy:
    if: github.event_name  == 'push'
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on staging
        if: github.ref == 'refs/heads/staging'
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.STAGING_DEPLOY_HOOK }}
          method: "POST"
      - name: Deploy on production
        if: github.ref == 'refs/heads/master'
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.PRODUCTION_DEPLOY_HOOK }}
          method: "POST"
